exclude: 'recipe/meta.yaml|.pre-commit-config.yaml|.gitignore|^docs/|/migrations/|.idea/|/node_modules/|/venv/|/env/|/build/|/dist/|/\.git/|/\.hg/|/\.mypy_cache/|/\.tox/|/\.venv/|/\.svn/|/\.cache/|/\.pytest_cache/|/\.vscode/|/\.serverless/|/\.serverless_plugins/|/\.serverless_plugins/|/\.ser'
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
      - id: isort
        name: isort
        entry: isort
        language: python
      - id: flake8
        name: flake8
        entry: flake8
        language: python
      - id: bandit
        name: bandit
        entry: bandit
        language: python
